### ISSUE TITLE
[10.0] Issues Website Portal Medical Patient Form

### ISSUE THREAD

**Issue by woodbrettm** [LasLabs/vertical-medical#169]
Not sure if this is an issue with website_portal_medical_patient not injecting vals properly or something :|

````
Traceback (most recent call last):
  File "/opt/odoo/addons/website/models/ir_http.py", line 265, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/media/sf_odoo10dev/vertical-medical/website_portal_medical/controllers/main.py", line 51, in website_medical_form
    data = self.extract_data(model_record, **kwargs)
TypeError: extract_data() got an unexpected keyword argument 'birthdate_date'
````

here: https://github.com/LasLabs/vertical-medical/blob/release/10.0/website_portal_medical/controllers/main.py#L51

* Also the patient's gender is not being auto filled in the form

**Comment by woodbrettm** [comment]
Make sure to check website_portal_medical_patient_species installs and saves with the form when done
