### ISSUE TITLE
[10.0][BUG] medical: NameError: name 'supplier' is not defined

### ISSUE THREAD

**Issue by lasley** [LasLabs/vertical-medical#178]
NameError in patient contact kanban.

Medical => Patients => AnyPatient => [Contacts & Addresses] Create

```
https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1326
Traceback:
Error: NameError: name 'supplier' is not defined
    at PY_ensurepy (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1326:65)
    at Object.py.evaluate (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1441:8)
    at Object.py.evaluate (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1450:194)
    at Object.py.eval (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1454:284)
    at https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1593:110
    at iterator (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:14:183)
    at Function.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:69:526)
    at eval_contexts (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1591:136)
    at https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1593:253
    at iterator (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:14:183)
    at Function.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:69:526)
    at eval_contexts (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1591:136)
    at https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1593:253
    at iterator (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:14:183)
    at Function.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:69:526)
    at eval_contexts (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1591:136)
    at pyeval (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1605:24)
    at eval_arg (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1609:129)
    at Object.ensure_evaluated (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1612:11)
    at Class.call (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1476:8)
    at Class.default_get (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1746:100)
    at Class.default_get (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:1760:1611)
    at Class.prototype.(anonymous function) [as default_get] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:3009:559)
    at Class.load_defaults (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:2132:163)
    at Object.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:681)
    at fire (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:548:56)
    at fire (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:541:299)
    at Object.add [as done] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:542:467)
    at Object.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:772)
    at fire (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:541:299)
    at Object.add [as done] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:542:467)
    at Array.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:649)
    at Function.each (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:370:767)
    at Object.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:560)
    at Function.Deferred (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:548:194)
    at Object.then (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:525)
    at Class.do_show (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:2126:220)
    at Class.prototype.(anonymous function) [as do_show] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:3009:559)
    at https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:2228:223
    at https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:681
    at fire (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:541:299)
    at Object.add [as done] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:542:467)
    at Array.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:649)
    at Function.each (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:370:767)
    at Object.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:560)
    at Function.Deferred (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:548:194)
    at Object.then (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:525)
    at https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:2228:192
    at https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:681
    at fire (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:541:299)
    at Object.add [as done] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:542:467)
    at Array.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:649)
    at Function.each (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:370:767)
    at Object.<anonymous> (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:560)
    at Function.Deferred (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:548:194)
    at Object.then (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:547:525)
    at Class.open (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:2228:17)
    at Class.prototype.(anonymous function) [as open] (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:3009:559)
    at Class.add_record (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:4208:1089)
    at HTMLButtonElement.<anonymous> (https://pharm.laslabs.com/web/content/908-accb589/web.assets_backend.js:4237:618)
    at HTMLDivElement.dispatch (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:637:451)
    at HTMLDivElement.elemData.handle (https://pharm.laslabs.com/web/content/663-5838d75/web.assets_common.js:610:173)
```

**Comment by woodbrettm** [comment]
Fixed in #179
